# Generated by Django 6.0.7 on 2026-07-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کیف پول (تومان)'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_hold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی مسدود شده'),
        ),
    ]
