# Generated by Django 6.0.7 on 2026-07-23 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'درصدی'), ('FIXED', 'مبلغ ثابت')], default='PERCENT', max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار تخفیف (درصد یا تومان)')),
                ('apply_type', models.CharField(choices=[('ALL', 'همه محصولات'), ('SPECIFIC', 'محصولات خاص'), ('CATEGORY', 'دسته\u200cبندی خاص')], default='ALL', max_length=10, verbose_name='نوع اعمال')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='حداکثر مبلغ تخفیف')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='تعداد دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده برای هر کاربر')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='دسته\u200cبندی مشمول تخفیف')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('products', models.ManyToManyField(blank=True, to='store.product', verbose_name='محصولات مشمول تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon', verbose_name='کد تخفیف اعمال\u200cشده'),
        ),
    ]
